admin_key: "YOUR SSH KEY"

# user keys:
users:
  oauth2:
    ssh_key:
      - "{{ admin_key }}"

# oauth2 proxy related
github_client_id: "LETTERSANDFIGURES"

# store these variables in an encrypted vault
# see: https://docs.ansible.com/ansible/latest/user_guide/vault.html
github_client_secret : "{{ vault_github_client_secret }}"
oauth2_proxy_secret_cookie : "{{ vault_oauth2_proxy_secret_cookie }}"

# airbyte
airbyte_webapp_port: 8000

# certbot/nginx
admin_email: "you@yourcompany.com"
server_name: "internal.yourcompany.com"
