- name: Create a oauth2-proxy with nginx in front.
  hosts: webservers
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: custom-users, tags: ['users'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: swap, tags: ['swap'] }
    - { role: docker, tags: ['docker'] }
      # basic nginx role, used to provision cert
    - { role: nginx-certbot, tags: ['nginx'] }
      # nginx configured with TLS support
    - { role: nginx-reverse-proxy, tags: ['nginx'] }
    - { role: airbyte, tags: ['airbyte'] }
    - { role: oauth2-proxy, tags: ['oauth2'] }
