- name: Create a oauth2-proxy with nginx in front.
  hosts: webservers
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: custom-users, tags: ['users'] }
    - { role: security, tags: ['security'] }
    - { role: swap, tags: ['swap'] }
    - { role: docker, tags: ['docker'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: oauth2-proxy, tag: ['oauth2'] }
